### PR TITLE
Fixed the problem where a server-side side panel was not rendered

### LINKED ISSUE #476: Initially selected extension panels are not rendered
If the last selected panel was an extension panel, its content will not be rendered the next time the viewer is reloaded.
Switching to another panel an comping back to extension panel renders the content correctly.

### PR DESCRIPTION
**Pull request by forman**
Fixed the problem where a server-side side panel was not rendered after app start, if it was the initially selected one.

Closes #476

### CODE REVIEW

File: src/connected/SidePanel.tsx [hunk 1]
```diff
@@ -113,25 +107,32 @@ function SidePanelImpl({
...
+      const contribIndex = contributedPanelsMap.get(sidebarPanelId)!;
+      const panelModel = contributedPanels[contribIndex];
+      if (!panelModel.componentRequested) {
+        // This will trigger loading the server-side
+        // UI component from endpoint /viewer/ext/layout
+        updateContributionContainer<PanelModel>(
+          "panels",
+          contribIndex,
+          {
+            componentRequested: true,
```
Comment (b-yogesh) [inline src/connected/SidePanel.tsx:122]: This is an app (host) specific solution and the reason this is done because we do not check deeply inside the chartlets library for the state change. As far as I understand, it will always return false for the `===` check because we create a new reference everytime we call the `updateContributionContainer`. So the suggestion is to change the Chartlets code to use deep equal instead of shallow.  Was there a reason why we only do a shallow comparison there?
And by this doing, we avoid adding new property like `componentRequested` to the `PanelModel`. What do you think?

P.S. I tried it and it works by using DeepEqual (custom function) and without using any if statements or `componentRequested`.

**Review by b-yogesh — COMMENTED** [review]
I think we should do the changes on the Chartlets side instead of doing it on every app that uses Chartlets. Please see the comment below

File: src/connected/SidePanel.tsx (hunk 1 above)
Comment (b-yogesh) [reply src/connected/SidePanel.tsx:122]: Thanks for the reply.
1. If deep-equal should not be the default, then what we are comparing in Chartlets with `===` does not make sense to me unless we are comparing primitives which we are not. (not related to this PR, but I am curious)
2. What I meant with deep equality was that it will save us one render cycle as no state will be updated if the layout is already loaded. Of course it is up to the host application to decide whether they want show their panel or not, but for that we have the `visible` prop already.
3. Yes, that sounds like a good idea to a hook to know if the layout has already been loaded.
4. Yes the comment applies here because `componentRequested` was introduced in this PR.

Comment (forman) [reply src/connected/SidePanel.tsx:122]: > If deep-equal should not be the default, then what we are comparing in Chartlets with === does not make sense to me unless we are comparing primitives which we are not. (not related to this PR, but I am curious)

Of course i makes sense. That's how most state management libs work, see Redux or Zustand. If the state objects is the same, nothing changed.

> Of course it is up to the host application to decide whether they want show their panel or not, but for that we have the visible prop already.

Where is that?

> Yes the comment applies here because componentRequested was introduced in this PR.

No, wen don't. It is just the renamed `visible`, because `visible` does not name the purpose.

Comment (b-yogesh) [reply src/connected/SidePanel.tsx:122]: > This is just the renamed visible, because visible does not name the purpose.

Oh, you are right. I missed this. This makes sense now.

> Of course it makes sense.

I will look up on the Zustand state objects comparison to have a better clarity.

**Review by b-yogesh — APPROVED** [review]
